"use client";
import { useEffect, useMemo, useState } from "react";
type Mode="smc"|"elliott"|"combined"; type Candle={time:number;open:number;high:number;low:number;close:number;volume:number};
const intervals=["1m","5m","15m","1h","4h","1d"] as const;
export default function Home(){
 const [mode,setMode]=useState<Mode>("smc"),[symbol,setSymbol]=useState("BTCUSDT"),[interval,setInterval]=useState<(typeof intervals)[number]>("15m"),[candles,setCandles]=useState<Candle[]>([]),[connected,setConnected]=useState(false);
 useEffect(()=>{let ws:WebSocket|undefined,stop=false;(async()=>{try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${interval}&limit=120`);const rows=await r.json();if(stop)return;setCandles(rows.map((x:any)=>({time:x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]})));ws=new WebSocket(`wss://stream.binance.com:9443/ws/${symbol.toLowerCase()}@kline_${interval}`);ws.onopen=()=>setConnected(true);ws.onclose=()=>setConnected(false);ws.onerror=()=>setConnected(false);ws.onmessage=e=>{const k=JSON.parse(e.data).k,c={time:k.t,open:+k.o,high:+k.h,low:+k.l,close:+k.c,volume:+k.v};setCandles(p=>{const a=[...p],i=a.findIndex(x=>x.time===c.time);if(i>=0)a[i]=c;else a.push(c);return a.slice(-120)})}}catch{setConnected(false)}})();return()=>{stop=true;ws?.close()}},[symbol,interval]);
 const analysis=useMemo(()=>{if(!candles.length)return null;const a=candles.slice(-30),hi=Math.max(...a.map(x=>x.high)),lo=Math.min(...a.map(x=>x.low)),last=candles.at(-1)!;return {last,hi,lo,trend:last.close>(hi+lo)/2?"Bullish":"Bearish"}},[candles]);
 return <main className="page"><header className="top"><div><div className="brand">QUANT<span>STRUCTURE</span></div><small>Live Crypto Market Analysis</small></div><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT"].map(x=><option key={x}>{x}</option>)}</select><div className="tf">{intervals.map(x=><button className={interval===x?"active":""} onClick={()=>setInterval(x)} key={x}>{x}</button>)}</div><span className={connected?"live":"offline"}>{connected?"● LIVE":"○ OFFLINE"}</span></header>
 <section className="tabs"><button className={mode==="smc"?"selected":""} onClick={()=>setMode("smc")}>SMC ANALYSIS</button><button className={mode==="elliott"?"selected":""} onClick={()=>setMode("elliott")}>ELLIOTT WAVE</button><button className={mode==="combined"?"selected":""} onClick={()=>setMode("combined")}>COMBINED</button></section>
 <section className="grid"><div className="chart card"><div className="cardhead"><b>{symbol} · {interval}</b><span>{candles.length} candles</span></div><div className="chartarea"><svg viewBox="0 0 1000 420" preserveAspectRatio="none">{[70,140,210,280,350].map(y=><line key={y} x1="0" x2="1000" y1={y} y2={y} stroke="currentColor" opacity=".08"/>)}{candles.length>1&&<polyline fill="none" stroke="currentColor" strokeWidth="2.5" points={candles.map((c,i)=>{const hi=Math.max(...candles.map(x=>x.high)),lo=Math.min(...candles.map(x=>x.low));return `${i*980/(candles.length-1)+10},${400-(c.close-lo)/(hi-lo||1)*360}`}).join(" ")}/>} {mode!=="elliott"&&<><text x="700" y="80" className="label">SMC STRUCTURE</text><text x="520" y="300" className="label">FVG / LIQUIDITY</text></>}{mode!=="smc"&&<><text x="120" y="330" className="wave">1</text><text x="260" y="275" className="wave">2</text><text x="430" y="150" className="wave">3</text><text x="610" y="230" className="wave">4</text><text x="800" y="115" className="wave">5?</text></>}</svg></div></div>
 <aside className="panel card"><h3>{mode==="smc"?"SMC ANALYSIS":mode==="elliott"?"ELLIOTT WAVE":"COMBINED ANALYSIS"}</h3>{analysis&&(mode==="smc"||mode==="combined")&&<><Row k="Trend" v={analysis.trend}/><Row k="Last Price" v={analysis.last.close.toFixed(2)}/><Row k="Structure" v="Live calculation"/><Row k="BOS / CHOCH" v="Engine active"/><Row k="FVG" v="Engine active"/><Row k="Liquidity" v="Engine active"/></>}{(mode==="elliott"||mode==="combined")&&<><Row k="Wave Structure" v="Candidate count"/><Row k="Primary Count" v="1 → 2 → 3 → 4 → 5"/><Row k="Alternative" v="Calculating"/><Row k="Fibonacci" v="Calculating"/><Row k="Invalidation" v="Calculating"/></>}</aside></section>
 <section className="bottom"><div className="card"><h3>Data Feed</h3><p>Binance public market data · WebSocket kline stream</p><small>Live candle updates enabled.</small></div><div className="card"><h3>Signal</h3><div className="signal">ANALYSIS ONLY</div><small>No automatic order execution.</small></div></section></main>}
function Row({k,v}:{k:string,v:string}){return <div className="row"><span>{k}</span><b>{v}</b></div>}