"use client";
import { useEffect, useMemo, useState } from "react";
import { analyzeSMC, analyzeElliott, Candle } from "../src/analysis/engine";
type Mode="smc"|"elliott"|"combined";
const intervals=["1m","5m","15m","1h","4h","1d"] as const;
export default function Home(){
 const [mode,setMode]=useState<Mode>("smc"),[symbol,setSymbol]=useState("BTCUSDT"),[interval,setInterval]=useState<(typeof intervals)[number]>("15m"),[candles,setCandles]=useState<Candle[]>([]),[connected,setConnected]=useState(false);
 useEffect(()=>{let ws:WebSocket|undefined,stop=false;(async()=>{try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${interval}&limit=160`);const rows=await r.json();if(stop)return;setCandles(rows.map((x:any)=>({time:x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]})));ws=new WebSocket(`wss://stream.binance.com:9443/ws/${symbol.toLowerCase()}@kline_${interval}`);ws.onopen=()=>setConnected(true);ws.onclose=()=>setConnected(false);ws.onerror=()=>setConnected(false);ws.onmessage=e=>{const k=JSON.parse(e.data).k,c={time:k.t,open:+k.o,high:+k.h,low:+k.l,close:+k.c,volume:+k.v};setCandles(p=>{const a=[...p],i=a.findIndex(x=>x.time===c.time);if(i>=0)a[i]=c;else a.push(c);return a.slice(-160)})}}catch{setConnected(false)}})();return()=>{stop=true;ws?.close()}},[symbol,interval]);
 const smc=useMemo(()=>analyzeSMC(candles),[candles]),elliott=useMemo(()=>analyzeElliott(candles),[candles]);
 const range=useMemo(()=>{const v=candles.slice(-100),hi=Math.max(...v.map(x=>x.high),0),lo=Math.min(...v.map(x=>x.low),0);return{hi,lo}},[candles]);
 const y=(p:number)=>390-(p-range.lo)/(range.hi-range.lo||1)*350, x=(i:number)=>10+i*980/Math.max(1,candles.length-1);
 return <main className="page"><header className="top"><div><div className="brand">QUANT<span>STRUCTURE</span></div><small>Live Crypto Market Analysis</small></div><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT"].map(s=><option key={s}>{s}</option>)}</select><div className="tf">{intervals.map(t=><button className={interval===t?"active":""} onClick={()=>setInterval(t)} key={t}>{t}</button>)}</div><span className={connected?"live":"offline"}>{connected?"● LIVE":"○ OFFLINE"}</span></header>
 <section className="tabs"><button className={mode==="smc"?"selected":""} onClick={()=>setMode("smc")}>SMC ANALYSIS</button><button className={mode==="elliott"?"selected":""} onClick={()=>setMode("elliott")}>ELLIOTT WAVE</button><button className={mode==="combined"?"selected":""} onClick={()=>setMode("combined")}>COMBINED</button></section>
 <section className="grid"><div className="chart card"><div className="cardhead"><b>{symbol} · {interval}</b><span>{candles.length} candles</span></div><div className="chartarea"><svg viewBox="0 0 1000 420" preserveAspectRatio="none">{[70,140,210,280,350].map(g=><line key={g} x1="0" x2="1000" y1={g} y2={g} stroke="currentColor" opacity=".08"/>)}{candles.length>1&&<polyline fill="none" stroke="currentColor" strokeWidth="2.5" points={candles.map((c,i)=>`${x(i)},${y(c.close)}`).join(" ")}/>}
 {mode!=="elliott"&&<>{smc.pivots.slice(-16).map((p,i)=><g key={"p"+i}><circle cx={x(p.index)} cy={y(p.price)} r="4"/><text x={x(p.index)+5} y={y(p.price)-6} className="label">{p.label}</text></g>)}{smc.events.map((e,i)=><text key={"e"+i} x={x(e.index)} y={y(e.price)-14} className="label">{e.type}</text>)}{smc.fvgs.map((f,i)=><rect key={"f"+i} x={x(f.from)} y={y(f.high)} width={Math.max(10,x(f.to)-x(f.from))} height={Math.max(3,y(f.low)-y(f.high))} opacity=".16"/>)}</>}
 {mode!=="smc"&&elliott.primary?.points.map((p,i)=><g key={"w"+i}><circle cx={x(p.index)} cy={y(p.price)} r="5"/><text x={x(p.index)+7} y={y(p.price)-8} className="wave">{p.label}</text></g>)}</svg></div></div>
 <aside className="panel card"><h3>{mode==="smc"?"SMC ANALYSIS":mode==="elliott"?"ELLIOTT WAVE":"COMBINED ANALYSIS"}</h3>{(mode==="smc"||mode==="combined")&&<><Row k="Trend" v={smc.trend}/><Row k="Structure" v={smc.pivots.at(-1)?.label||"—"}/><Row k="BOS / CHOCH" v={smc.events.at(-1)?.type||"None"}/><Row k="FVG" v={String(smc.fvgs.length)}/><Row k="Order Blocks" v={String(smc.orderBlocks.length)}/><Row k="Liquidity" v={`${smc.liquidityHighs.length}H / ${smc.liquidityLows.length}L`}/><Row k="P/D" v={smc.premiumDiscount}/><Row k="SMC Score" v={smc.score+"/100"}/></>}{(mode==="elliott"||mode==="combined")&&<><Row k="Phase" v={elliott.phase}/><Row k="Primary" v={elliott.primary?elliott.primary.points.map(p=>p.label).join(" → "):"No candidate"}/><Row k="Direction" v={elliott.primary?.direction||"—"}/><Row k="Alternative" v={elliott.alternative?"Available":"None"}/><Row k="Fib 2/1" v={elliott.fib?.r21.toString()||"—"}/><Row k="Fib 3/1" v={elliott.fib?.r31.toString()||"—"}/><Row k="Invalidation" v={elliott.primary?.invalidation.toFixed(2)||"—"}/><Row k="Wave Score" v={elliott.score+"/100"}/></>}</aside></section>
 <section className="bottom"><div className="card"><h3>Data Feed</h3><p>Binance public market data · WebSocket kline stream</p><small>Live candle updates enabled.</small></div><div className="card"><h3>Signal</h3><div className="signal">ANALYSIS ONLY</div><small>SMC and Elliott engines are independent. No automatic order execution.</small></div></section></main>}
function Row({k,v}:{k:string,v:string}){return <div className="row"><span>{k}</span><b>{v}</b></div>}
