"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { createChart, CandlestickSeries, LineSeries, LineStyle } from "lightweight-charts";
import { analyzeSMC, analyzeElliott, Candle } from "../src/analysis/engine";
type Mode="smc"|"elliott"|"combined";
const intervals=["1m","5m","15m","1h","4h","1d"] as const;
export default function Home(){
 const [mode,setMode]=useState<Mode>("smc"),[symbol,setSymbol]=useState("BTCUSDT"),[interval,setInterval]=useState<(typeof intervals)[number]>("15m"),[candles,setCandles]=useState<Candle[]>([]),[connected,setConnected]=useState(false),chartRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{let ws:WebSocket|undefined,stop=false;(async()=>{try{const r=await fetch(`https://api.binance.com/api/v3/klines?symbol=${symbol}&interval=${interval}&limit=200`);const rows=await r.json();if(stop)return;setCandles(rows.map((x:any)=>({time:x[0],open:+x[1],high:+x[2],low:+x[3],close:+x[4],volume:+x[5]})));ws=new WebSocket(`wss://stream.binance.com:9443/ws/${symbol.toLowerCase()}@kline_${interval}`);ws.onopen=()=>setConnected(true);ws.onclose=()=>setConnected(false);ws.onerror=()=>setConnected(false);ws.onmessage=e=>{const k=JSON.parse(e.data).k,c={time:k.t,open:+k.o,high:+k.h,low:+k.l,close:+k.c,volume:+k.v};setCandles(p=>{const a=[...p],i=a.findIndex(x=>x.time===c.time);if(i>=0)a[i]=c;else a.push(c);return a.slice(-200)})}}catch{setConnected(false)}})();return()=>{stop=true;ws?.close()}},[symbol,interval]);
 const smc=useMemo(()=>analyzeSMC(candles),[candles]),elliott=useMemo(()=>analyzeElliott(candles),[candles]);
 useEffect(()=>{if(!chartRef.current||candles.length<2)return;const el=chartRef.current;el.innerHTML="";const chart=createChart(el,{height:440,layout:{background:{color:"#0e131c"},textColor:"#8d99ad"},grid:{vertLines:{color:"#151d29"},horzLines:{color:"#151d29"}},rightPriceScale:{borderColor:"#263143"},timeScale:{borderColor:"#263143",timeVisible:true}});const series=chart.addSeries(CandlestickSeries,{upColor:"#49d88b",downColor:"#ef6b73",borderVisible:false,wickUpColor:"#49d88b",wickDownColor:"#ef6b73"});series.setData(candles.map(c=>({time:Math.floor(c.time/1000) as any,open:c.open,high:c.high,low:c.low,close:c.close})));
 if(mode!=="elliott"){const eventLines=smc.events.map(e=>({price:e.price,color:e.direction==="bullish"?"#49d88b":"#ef6b73",lineWidth:1 as any,lineStyle:LineStyle.Dashed,axisLabelVisible:true,title:e.type}));series.createPriceLine(eventLines.at(-1)||{price:candles.at(-1)!.close,color:"#8ba7ff",lineWidth:1 as any,lineStyle:LineStyle.Dashed,axisLabelVisible:false,title:""});smc.orderBlocks.slice(-4).forEach(o=>series.createPriceLine({price:o.low,color:o.type==="bullish"?"#49d88b":"#ef6b73",lineWidth:1 as any,lineStyle:LineStyle.Dotted,axisLabelVisible:true,title:"OB"}));smc.liquidityHighs.slice(-3).forEach(p=>series.createPriceLine({price:p.price,color:"#d8b35c",lineWidth:1 as any,lineStyle:LineStyle.Dotted,axisLabelVisible:true,title:"LQH"}));smc.liquidityLows.slice(-3).forEach(p=>series.createPriceLine({price:p.price,color:"#d8b35c",lineWidth:1 as any,lineStyle:LineStyle.Dotted,axisLabelVisible:true,title:"LQL"}));}
 if(mode!=="smc"&&elliott.primary){const pts=elliott.primary.points.map(p=>({time:Math.floor(candles[p.index].time/1000) as any,value:p.price}));const ls=chart.addSeries(LineSeries,{lineWidth:2,color:"#c084fc"});ls.setData(pts);}
 chart.timeScale().fitContent();const ro=new ResizeObserver(()=>chart.applyOptions({width:el.clientWidth}));ro.observe(el);return()=>{ro.disconnect();chart.remove()}},[candles,mode,smc,elliott]);
 return <main className="page"><header className="top"><div><div className="brand">QUANT<span>STRUCTURE</span></div><small>Live Crypto Market Analysis</small></div><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT"].map(s=><option key={s}>{s}</option>)}</select><div className="tf">{intervals.map(t=><button className={interval===t?"active":""} onClick={()=>setInterval(t)} key={t}>{t}</button>)}</div><span className={connected?"live":"offline"}>{connected?"● LIVE":"○ OFFLINE"}</span></header>
 <section className="tabs"><button className={mode==="smc"?"selected":""} onClick={()=>setMode("smc")}>SMC ANALYSIS</button><button className={mode==="elliott"?"selected":""} onClick={()=>setMode("elliott")}>ELLIOTT WAVE</button><button className={mode==="combined"?"selected":""} onClick={()=>setMode("combined")}>COMBINED</button></section>
 <section className="grid"><div className="chart card"><div className="cardhead"><b>{symbol} · {interval}</b><span>{candles.length} candles</span></div><div className="chartarea" ref={chartRef}/></div>
 <aside className="panel card"><h3>{mode==="smc"?"SMC ANALYSIS":mode==="elliott"?"ELLIOTT WAVE":"COMBINED ANALYSIS"}</h3>{(mode==="smc"||mode==="combined")&&<><Row k="Trend" v={smc.trend}/><Row k="Structure" v={smc.pivots.at(-1)?.label||"—"}/><Row k="BOS / CHOCH" v={smc.events.at(-1)?.type||"None"}/><Row k="FVG" v={String(smc.fvgs.length)}/><Row k="Order Blocks" v={String(smc.orderBlocks.length)}/><Row k="Liquidity" v={`${smc.liquidityHighs.length}H / ${smc.liquidityLows.length}L`}/><Row k="P/D" v={smc.premiumDiscount}/><Row k="SMC Score" v={smc.score+"/100"}/></>}{(mode==="elliott"||mode==="combined")&&<><Row k="Phase" v={elliott.phase}/><Row k="Primary" v={elliott.primary?elliott.primary.points.map(p=>p.label).join(" → "):"No candidate"}/><Row k="Direction" v={elliott.primary?.direction||"—"}/><Row k="Alternative" v={elliott.alternative?"Available":"None"}/><Row k="Fib 2/1" v={elliott.fib?.r21.toString()||"—"}/><Row k="Fib 3/1" v={elliott.fib?.r31.toString()||"—"}/><Row k="Invalidation" v={elliott.primary?.invalidation.toFixed(2)||"—"}/><Row k="Wave Score" v={elliott.score+"/100"}/></>}</aside></section>
 <section className="bottom"><div className="card"><h3>Data Feed</h3><p>Binance public market data · WebSocket kline stream</p><small>Live candle updates enabled.</small></div><div className="card"><h3>Signal</h3><div className="signal">ANALYSIS ONLY</div><small>Independent SMC / Elliott engines · No automatic order execution.</small></div></section></main>}
function Row({k,v}:{k:string,v:string}){return <div className="row"><span>{k}</span><b>{v}</b></div>}
