export type Candle={time:number;open:number;high:number;low:number;close:number;volume:number};
export type Pivot={index:number;price:number;type:"H"|"L";label?:string};
export type FVG={from:number;to:number;low:number;high:number;type:"bullish"|"bearish"};
export type OB={index:number;low:number;high:number;type:"bullish"|"bearish"};
export type StructureEvent={index:number;price:number;type:"BOS"|"CHOCH";direction:"bullish"|"bearish"};
export type SMCResult={trend:"Bullish"|"Bearish"|"Neutral";pivots:Pivot[];events:StructureEvent[];fvgs:FVG[];orderBlocks:OB[];liquidityHighs:Pivot[];liquidityLows:Pivot[];premiumDiscount:"Premium"|"Discount"|"Equilibrium";score:number};
export type WavePoint={index:number;price:number;label:string};
export type WaveCount={points:WavePoint[];kind:"Impulse"|"Correction";direction:"bullish"|"bearish";invalidation:number;targets:number[];quality:number};
export type ElliottResult={primary:WaveCount|null;alternative:WaveCount|null;fib:{r21:number;r31:number;r41:number;r51:number}|null;phase:string;score:number};

function atr(c:Candle[],n=14){if(c.length<n+1)return c.length? (c.at(-1)!.high-c.at(-1)!.low):0;let s=0;for(let i=c.length-n;i<c.length;i++)s+=c[i].high-c[i].low;return s/n}
function pivots(c:Candle[],w=3):Pivot[]{const out:Pivot[]=[];for(let i=w;i<c.length-w;i++){let hi=true,lo=true;for(let j=i-w;j<=i+w;j++){if(j===i)continue;if(c[j].high>c[i].high)hi=false;if(c[j].low<c[i].low)lo=false}if(hi)out.push({index:i,price:c[i].high,type:"H"});if(lo)out.push({index:i,price:c[i].low,type:"L"})}return out.sort((a,b)=>a.index-b.index)}
export function analyzeSMC(c:Candle[]):SMCResult{if(c.length<10)return{trend:"Neutral",pivots:[],events:[],fvgs:[],orderBlocks:[],liquidityHighs:[],liquidityLows:[],premiumDiscount:"Equilibrium",score:0};const ps=pivots(c,3), labeled:Pivot[]=[];let lastH:number|undefined,lastL:number|undefined;for(const p of ps){const q={...p};if(p.type==="H"){q.label=lastH===undefined?"SH":p.price>lastH?"HH":"LH";lastH=p.price}else{q.label=lastL===undefined?"SL":p.price>lastL?"HL":"LL";lastL=p.price}labeled.push(q)}
const events:StructureEvent[]=[];let trend:"bullish"|"bearish"|null=null;for(const p of labeled){if(p.type==="H"&&(p.label==="HH"||p.label==="LH")){const broken=c.slice(p.index+1).some(x=>x.close>p.price);if(broken){const d="bullish";events.push({index:p.index,price:p.price,type:trend&&trend!==d?"CHOCH":"BOS",direction:d});trend=d}}if(p.type==="L"&&(p.label==="LL"||p.label==="HL")){const broken=c.slice(p.index+1).some(x=>x.close<p.price);if(broken){const d="bearish";events.push({index:p.index,price:p.price,type:trend&&trend!==d?"CHOCH":"BOS",direction:d});trend=d}}}
const fvgs:FVG[]=[];for(let i=1;i<c.length-1;i++){if(c[i-1].high<c[i+1].low)fvgs.push({from:i-1,to:i+1,low:c[i-1].high,high:c[i+1].low,type:"bullish"});if(c[i-1].low>c[i+1].high)fvgs.push({from:i-1,to:i+1,low:c[i+1].high,high:c[i-1].low,type:"bearish"})}
const orderBlocks:OB[]=[];const a=atr(c);for(let i=1;i<c.length-1;i++){if(c[i].close<c[i].open&&c[i+1].close>c[i].high+a*.15)orderBlocks.push({index:i,low:c[i].low,high:c[i].open,type:"bullish"});if(c[i].close>c[i].open&&c[i+1].close<c[i].low-a*.15)orderBlocks.push({index:i,low:c[i].open,high:c[i].high,type:"bearish"})}
const highs=labeled.filter(p=>p.type==="H"),lows=labeled.filter(p=>p.type==="L");const tol=a*.35;const lh=highs.filter((p,i)=>highs.slice(0,i).some(x=>Math.abs(x.price-p.price)<=tol));const ll=lows.filter((p,i)=>lows.slice(0,i).some(x=>Math.abs(x.price-p.price)<=tol));const last=c.at(-1)!;const hi=Math.max(...c.slice(-30).map(x=>x.high)),lo=Math.min(...c.slice(-30).map(x=>x.low)),mid=(hi+lo)/2;const trendOut=last.close>mid?"Bullish":last.close<mid?"Bearish":"Neutral";const pd=last.close>mid?"Premium":last.close<mid?"Discount":"Equilibrium";const score=Math.max(0,Math.min(100,50+(events.at(-1)?.direction===trendOut.toLowerCase()?20:0)+(fvgs.slice(-3).length*5)+(lh.length+ll.length>0?5:0)));return{trend:trendOut,pivots:labeled,events:events.slice(-8),fvgs:fvgs.slice(-8),orderBlocks:orderBlocks.slice(-6),liquidityHighs:lh.slice(-5),liquidityLows:ll.slice(-5),premiumDiscount:pd,score:Math.round(score)}}
function fib(a:number,b:number,r:number){return a+(b-a)*r}
function makeWave(c:Candle[],bull=true):WaveCount|null{const ps=pivots(c,2);const candidates=ps.slice(-9);if(candidates.length<5)return null;let best:WaveCount|null=null;for(let s=0;s<=candidates.length-5;s++){const q=candidates.slice(s,s+5);const ok=q.every((p,i)=>i===0||p.index>q[i-1].index)&&(bull?q[0].type==="L"&&q[1].type==="H"&&q[2].type==="L"&&q[3].type==="H"&&q[4].type==="L":q[0].type==="H"&&q[1].type==="L"&&q[2].type==="H"&&q[3].type==="L"&&q[4].type==="H");if(!ok)continue;const p=q.map(x=>x.price),w1=Math.abs(p[1]-p[0]),w2=Math.abs(p[2]-p[1]),w3=Math.abs(p[3]-p[2]),w4=Math.abs(p[4]-p[3]);if(w1===0||w3===0)continue;const retr=w2/w1,ext=w3/w1;const quality=Math.max(0,100-Math.abs(retr-.5)*100-Math.max(0,1-ext)*30);const inv=bull?p[0]:p[0];const target=bull?[p[0]+w1*1.618,p[0]+w1*2.618]:[p[0]-w1*1.618,p[0]-w1*2.618];const wc:WaveCount={points:q.map((x,i)=>({index:x.index,price:x.price,label:String(i+1)})),kind:"Impulse",direction:bull?"bullish":"bearish",invalidation:inv,targets:target,quality:Math.round(quality)};if(!best||wc.quality>best.quality)best=wc}return best}
export function analyzeElliott(c:Candle[]):ElliottResult{if(c.length<20)return{primary:null,alternative:null,fib:null,phase:"Insufficient data",score:0};const bull=makeWave(c,true),bear=makeWave(c,false),primary=(bull?.quality??0)>=(bear?.quality??0)?bull:bear,alternative=primary===bull?bear:bull;if(!primary)return{primary:null,alternative:null,fib:null,phase:"No valid candidate",score:0};const p=primary.points.map(x=>x.price);const w1=Math.abs(p[1]-p[0]),w2=Math.abs(p[2]-p[1]),w3=Math.abs(p[3]-p[2]),w4=Math.abs(p[4]-p[3]);return{primary,alternative,fib:{r21:+(w2/w1).toFixed(3),r31:+(w3/w1).toFixed(3),r41:+(w4/w3).toFixed(3),r51:+(primary.targets[0]-p[0]).toFixed(2)},phase:"Impulse candidate",score:primary.quality}}
